// 25 ultra-realistic demo leads for Nick Flores Sr. — Team Flores CRM
// Covers all 8 stages, NV/AZ/CA/FL/TX, multiple sources
// rowNumber 2–26

export const MOCK_LEADS = [
  // ── 1. Maria Garcia — NV — CONTACTED ────────────────────────────────────────
  {
    rowNumber: 2,
    'Date': '2026-03-21',
    'First Name': 'Maria',
    'Last Name': 'Garcia',
    'Email': 'maria.garcia@gmail.com',
    'Phone': '(702) 318-4521',
    'Zip Code': '89117',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '435000',
    'Down Payment': '87000',
    'Rate Type': 'Fixed',
    'Annual Income': '120000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'LeadPops NV Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/home-purchase',
    'Date Submitted': '2026-03-21',
    'Time Submitted': '02:30 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-21T14:30:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-03-22 09:05] Text sent using LeadPops NV Purchase template. Email intro sent. Awaiting response.',
  },

  // ── 2. James Wilson — AZ — QUALIFIED ────────────────────────────────────────
  {
    rowNumber: 3,
    'Date': '2026-03-10',
    'First Name': 'James',
    'Last Name': 'Wilson',
    'Email': 'james.wilson@gmail.com',
    'Phone': '(480) 445-7832',
    'Zip Code': '85251',
    'State': 'AZ',
    'Loan Type': 'VA Loan',
    'VA Loan': 'Yes',
    'Property Type': 'Single Family',
    'Credit Score': '700-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '395000',
    'Down Payment': '0',
    'Rate Type': 'Fixed',
    'Annual Income': '92000',
    'Employment Status': 'Veteran',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-10',
    'Time Submitted': '10:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-10T10:00:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-03-20 10:00] VA certificate of eligibility received. Pre-approval letter issued. Reviewing properties in Scottsdale.\n[2026-03-12 10:30] Call completed. Veteran using VA benefit for first home. Very motivated.',
  },

  // ── 3. Sarah Johnson — NV — CLOSED WON ──────────────────────────────────────
  {
    rowNumber: 4,
    'Date': '2026-02-01',
    'First Name': 'Sarah',
    'Last Name': 'Johnson',
    'Email': 'sarah.johnson@gmail.com',
    'Phone': '(702) 562-9043',
    'Zip Code': '89134',
    'State': 'NV',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Loan Balance': '310000',
    'Property Value': '520000',
    'Rate Type': 'Fixed',
    'Annual Income': '148000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate NV Refi',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-02-01',
    'Time Submitted': '03:00 PM',
    'Browser': 'Safari',
    'Submitted At': '2026-02-01T15:00:00Z',
    'Status': 'Closed Won',
    'Notes': '[2026-03-14 15:00] LOAN FUNDED! Sarah refinanced her primary residence in Summerlin. Lowered rate by 1.2%. Monthly savings $415/mo. Excellent client — referred two coworkers.\n[2026-02-05 10:00] Initial disclosures sent.\n[2026-02-03 09:00] Call completed. Very interested in refinancing to lower rate.',
  },

  // ── 4. Robert Martinez — TX — NEW ───────────────────────────────────────────
  {
    rowNumber: 5,
    'Date': '2026-03-28',
    'First Name': 'Robert',
    'Last Name': 'Martinez',
    'Email': 'robert.martinez@gmail.com',
    'Phone': '(214) 234-6780',
    'Zip Code': '75201',
    'State': 'TX',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '680-699',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '355000',
    'Down Payment': '17750',
    'Rate Type': 'Fixed',
    'Annual Income': '82000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate TX Purchase',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-28',
    'Time Submitted': '09:15 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-28T09:15:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 5. Jennifer Lee — CA — ACTIVE ───────────────────────────────────────────
  {
    rowNumber: 6,
    'Date': '2026-03-15',
    'First Name': 'Jennifer',
    'Last Name': 'Lee',
    'Email': 'jennifer.lee@gmail.com',
    'Phone': '(714) 882-3047',
    'Zip Code': '92614',
    'State': 'CA',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '740-759',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '685000',
    'Down Payment': '137000',
    'Rate Type': 'Fixed',
    'Annual Income': '195000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-15',
    'Time Submitted': '11:30 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-15T11:30:00Z',
    'Status': 'Active',
    'Notes': '[2026-03-17 10:00] Call completed. Jennifer upgrading from condo to SFH in Irvine. Excellent income, strong buyer. Sending pre-approval link.',
  },

  // ── 6. Lisa Thompson — AZ — ACTIVE ──────────────────────────────────────────
  {
    rowNumber: 7,
    'Date': '2026-03-18',
    'First Name': 'Lisa',
    'Last Name': 'Thompson',
    'Email': 'lisa.thompson@gmail.com',
    'Phone': '(602) 773-5819',
    'Zip Code': '85016',
    'State': 'AZ',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '660-679',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '310000',
    'Down Payment': '10850',
    'Rate Type': 'Fixed',
    'Annual Income': '68000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'LeadPops AZ Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/home-purchase',
    'Date Submitted': '2026-03-18',
    'Time Submitted': '09:45 AM',
    'Browser': 'Firefox',
    'Submitted At': '2026-03-18T09:45:00Z',
    'Status': 'Active',
    'Notes': '[2026-03-19 11:00] Call completed. First-time buyer, FHA loan candidate. Discussed 3.5% down requirement. Request pay stubs.',
  },

  // ── 7. Michael Torres — NV — ACTIVE ─────────────────────────────────────────
  {
    rowNumber: 8,
    'Date': '2026-03-14',
    'First Name': 'Michael',
    'Last Name': 'Torres',
    'Email': 'michael.torres@gmail.com',
    'Phone': '(702) 677-5129',
    'Zip Code': '89144',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '720-739',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '515000',
    'Down Payment': '51500',
    'Rate Type': 'Fixed',
    'Annual Income': '138000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'LeadPops NV Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/home-purchase',
    'Date Submitted': '2026-03-14',
    'Time Submitted': '02:00 PM',
    'Browser': 'Edge',
    'Submitted At': '2026-03-14T14:00:00Z',
    'Status': 'Active',
    'Notes': '[2026-03-15 10:00] Call completed. Moving up from starter home. 10% down conventional. Strong income. Sending initial disclosures.',
  },

  // ── 8. Carlos Martinez — NV — COLD ──────────────────────────────────────────
  {
    rowNumber: 9,
    'Date': '2026-03-10',
    'First Name': 'Carlos',
    'Last Name': 'Martinez',
    'Email': 'carlos.martinez@gmail.com',
    'Phone': '(725) 204-8836',
    'Zip Code': '89101',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '620-639',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 1-3 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '445000',
    'Down Payment': '15575',
    'Rate Type': 'Fixed',
    'Annual Income': '72000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'LeadPops NV Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/home-purchase',
    'Date Submitted': '2026-03-10',
    'Time Submitted': '03:30 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-10T15:30:00Z',
    'Status': 'Cold',
    'Notes': '[2026-03-21 09:00] Third follow-up — no response. Marking cold. Will add to drip campaign.\n[2026-03-13 09:00] Left voicemail, sent email. No response.\n[2026-03-11 08:30] Intro text and email sent.',
  },

  // ── 9. Amanda Foster — NV — NEW ─────────────────────────────────────────────
  {
    rowNumber: 10,
    'Date': '2026-03-27',
    'First Name': 'Amanda',
    'Last Name': 'Foster',
    'Email': 'amanda.foster@gmail.com',
    'Phone': '(702) 523-6741',
    'Zip Code': '89138',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '700-719',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '395000',
    'Down Payment': '39500',
    'Rate Type': 'Fixed',
    'Annual Income': '98000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Bankrate NV Purchase',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-27',
    'Time Submitted': '11:20 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-27T11:20:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 10. Kevin Nguyen — CA — QUALIFIED ───────────────────────────────────────
  {
    rowNumber: 11,
    'Date': '2026-03-05',
    'First Name': 'Kevin',
    'Last Name': 'Nguyen',
    'Email': 'kevin.nguyen@gmail.com',
    'Phone': '(949) 338-7254',
    'Zip Code': '92660',
    'State': 'CA',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Loan Balance': '295000',
    'Property Value': '485000',
    'Rate Type': 'Fixed',
    'Annual Income': '162000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate NV Refi',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-05',
    'Time Submitted': '10:00 AM',
    'Browser': 'Safari',
    'Submitted At': '2026-03-05T10:00:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-03-15 10:00] Pre-approval issued. Rate locked. Excellent credit — lowering from 7.25% to 6.375%. Moving forward.\n[2026-03-08 09:30] Call completed. Looking to lower rate on Newport Beach SFH.',
  },

  // ── 11. Patricia Gonzalez — NV — IN PROGRESS ────────────────────────────────
  {
    rowNumber: 12,
    'Date': '2026-02-20',
    'First Name': 'Patricia',
    'Last Name': 'Gonzalez',
    'Email': 'patricia.gonzalez@gmail.com',
    'Phone': '(702) 834-5627',
    'Zip Code': '89148',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '720-739',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '520000',
    'Down Payment': '104000',
    'Rate Type': 'Fixed',
    'Annual Income': '142000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'LeadPops NV Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/home-purchase',
    'Date Submitted': '2026-02-20',
    'Time Submitted': '01:15 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-02-20T13:15:00Z',
    'Status': 'In Progress',
    'Notes': '[2026-03-26 10:00] Appraisal ordered. Awaiting underwriting decision. Rate lock expires 4/5.\n[2026-03-10 09:00] Pre-approval issued. Under contract on Summerlin property.\n[2026-02-25 10:30] Call completed. Moving up, 20% down conventional. Strong profile.',
  },

  // ── 12. Emily Chen — AZ — NEW ───────────────────────────────────────────────
  {
    rowNumber: 13,
    'Date': '2026-03-28',
    'First Name': 'Emily',
    'Last Name': 'Chen',
    'Email': 'emily.chen@gmail.com',
    'Phone': '(480) 614-9203',
    'Zip Code': '85281',
    'State': 'AZ',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Condo',
    'Credit Score': '660-679',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 1-3 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '285000',
    'Down Payment': '9975',
    'Rate Type': 'Fixed',
    'Annual Income': '74000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-28',
    'Time Submitted': '07:55 AM',
    'Browser': 'Safari',
    'Submitted At': '2026-03-28T07:55:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 13. Brandon Williams — FL — CONTACTED ───────────────────────────────────
  {
    rowNumber: 14,
    'Date': '2026-03-22',
    'First Name': 'Brandon',
    'Last Name': 'Williams',
    'Email': 'brandon.williams@gmail.com',
    'Phone': '(954) 338-7612',
    'Zip Code': '33309',
    'State': 'FL',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '640-659',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '445000',
    'Down Payment': '15575',
    'Rate Type': 'Fixed',
    'Annual Income': '89000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Website',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-22',
    'Time Submitted': '02:45 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-22T14:45:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-03-23 09:00] Intro email and text sent. Brandon responded — interested in FHA loan. Scheduled call for 3/25.',
  },

  // ── 14. Samantha Davis — NV — ACTIVE ────────────────────────────────────────
  {
    rowNumber: 15,
    'Date': '2026-03-12',
    'First Name': 'Samantha',
    'Last Name': 'Davis',
    'Email': 'samantha.davis@gmail.com',
    'Phone': '(702) 789-4523',
    'Zip Code': '89128',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '700-719',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '375000',
    'Down Payment': '18750',
    'Rate Type': 'Fixed',
    'Annual Income': '94000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'LeadPops NV Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/home-purchase',
    'Date Submitted': '2026-03-12',
    'Time Submitted': '12:30 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-12T12:30:00Z',
    'Status': 'Active',
    'Notes': '[2026-03-18 11:00] Send rate update email per Samantha request. She is comparison shopping.\n[2026-03-14 10:00] Call completed. 5% down conventional, first-time buyer. Pre-approval pending.',
  },

  // ── 15. David Kim — NV — COLD ────────────────────────────────────────────────
  {
    rowNumber: 16,
    'Date': '2026-03-21',
    'First Name': 'David',
    'Last Name': 'Kim',
    'Email': 'david.kim@gmail.com',
    'Phone': '(702) 614-3782',
    'Zip Code': '89129',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '620-639',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 3-6 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '295000',
    'Down Payment': '10325',
    'Rate Type': 'Fixed',
    'Annual Income': '65000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Website',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-21',
    'Time Submitted': '04:10 PM',
    'Browser': 'Firefox',
    'Submitted At': '2026-03-21T16:10:00Z',
    'Status': 'Cold',
    'Notes': '[2026-03-27 09:00] No response after 3 attempts. Added to monthly drip. Revisit in 60 days.\n[2026-03-22 09:00] Intro email sent. Left voicemail.',
  },

  // ── 16. Rachel Patel — CA — CONTACTED ───────────────────────────────────────
  {
    rowNumber: 17,
    'Date': '2026-03-19',
    'First Name': 'Rachel',
    'Last Name': 'Patel',
    'Email': 'rachel.patel@gmail.com',
    'Phone': '(818) 502-6341',
    'Zip Code': '91403',
    'State': 'CA',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '740-759',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '725000',
    'Down Payment': '145000',
    'Rate Type': 'Fixed',
    'Annual Income': '218000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-19',
    'Time Submitted': '10:30 AM',
    'Browser': 'Safari',
    'Submitted At': '2026-03-19T10:30:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-03-20 09:30] Intro email sent. Rachel replied — upgrading from condo in Sherman Oaks. Scheduling call.',
  },

  // ── 17. Anthony Rodriguez — TX — NEW ────────────────────────────────────────
  {
    rowNumber: 18,
    'Date': '2026-03-28',
    'First Name': 'Anthony',
    'Last Name': 'Rodriguez',
    'Email': 'anthony.rodriguez@gmail.com',
    'Phone': '(713) 882-4519',
    'Zip Code': '77002',
    'State': 'TX',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '600-619',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 1-3 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '265000',
    'Down Payment': '9275',
    'Rate Type': 'Fixed',
    'Annual Income': '58000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate TX Purchase',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-28',
    'Time Submitted': '08:10 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-28T08:10:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 18. Stephanie Nguyen — NV — IN PROGRESS ─────────────────────────────────
  {
    rowNumber: 19,
    'Date': '2026-02-15',
    'First Name': 'Stephanie',
    'Last Name': 'Nguyen',
    'Email': 'stephanie.nguyen@gmail.com',
    'Phone': '(702) 391-8840',
    'Zip Code': '89052',
    'State': 'NV',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Loan Balance': '278000',
    'Property Value': '462000',
    'Rate Type': 'Fixed',
    'Annual Income': '136000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'LeadPops NV Refi',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/refinance',
    'Date Submitted': '2026-02-15',
    'Time Submitted': '09:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-02-15T09:00:00Z',
    'Status': 'In Progress',
    'Notes': '[2026-03-25 10:00] Appraisal received at $462k. Underwriting review in progress. Closing target 4/10.\n[2026-03-01 09:00] Full application submitted. Income docs complete. Rate locked at 6.25%.',
  },

  // ── 19. Marcus Johnson — AZ — COLD ──────────────────────────────────────────
  {
    rowNumber: 20,
    'Date': '2026-03-05',
    'First Name': 'Marcus',
    'Last Name': 'Johnson',
    'Email': 'marcus.johnson@gmail.com',
    'Phone': '(520) 447-9231',
    'Zip Code': '85701',
    'State': 'AZ',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '640-659',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 3-6 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '335000',
    'Down Payment': '11725',
    'Rate Type': 'Fixed',
    'Annual Income': '75000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'LeadPops AZ Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/home-purchase',
    'Date Submitted': '2026-03-05',
    'Time Submitted': '02:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-05T14:00:00Z',
    'Status': 'Cold',
    'Notes': '[2026-03-20 09:00] No response after 4 follow-ups over 15 days. Moving to cold drip.\n[2026-03-06 08:30] Intro email and text sent.',
  },

  // ── 20. Diana Martinez — FL — CONTACTED ─────────────────────────────────────
  {
    rowNumber: 21,
    'Date': '2026-03-20',
    'First Name': 'Diana',
    'Last Name': 'Martinez',
    'Email': 'diana.martinez@gmail.com',
    'Phone': '(561) 774-8053',
    'Zip Code': '33401',
    'State': 'FL',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '680-699',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Loan Balance': '248000',
    'Property Value': '415000',
    'Rate Type': 'Fixed',
    'Annual Income': '102000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Website',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-20',
    'Time Submitted': '03:30 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-20T15:30:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-03-21 09:30] Intro email sent. Diana replied — wants to pull cash-out for home improvement. Scheduling consultation.',
  },

  // ── 21. Christopher Lee — NV — QUALIFIED ────────────────────────────────────
  {
    rowNumber: 22,
    'Date': '2026-03-08',
    'First Name': 'Christopher',
    'Last Name': 'Lee',
    'Email': 'christopher.lee@gmail.com',
    'Phone': '(702) 634-8172',
    'Zip Code': '89128',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '720-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '465000',
    'Down Payment': '93000',
    'Rate Type': 'Fixed',
    'Annual Income': '124000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Bankrate NV Purchase',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-08',
    'Time Submitted': '09:15 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-08T09:15:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-03-24 09:15] Pre-approval issued at $465k. COE not applicable. Touring Summerlin this weekend. Consultation scheduled.\n[2026-03-10 02:00 PM] Call completed. First-time buyer, strong profile, 20% down.',
  },

  // ── 22. Ashley Turner — AZ — ACTIVE ─────────────────────────────────────────
  {
    rowNumber: 23,
    'Date': '2026-03-16',
    'First Name': 'Ashley',
    'Last Name': 'Turner',
    'Email': 'ashley.turner@gmail.com',
    'Phone': '(602) 558-2974',
    'Zip Code': '85032',
    'State': 'AZ',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '660-679',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '298000',
    'Down Payment': '14900',
    'Rate Type': 'Fixed',
    'Annual Income': '78000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'LeadPops AZ Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/home-purchase',
    'Date Submitted': '2026-03-16',
    'Time Submitted': '01:00 PM',
    'Browser': 'Safari',
    'Submitted At': '2026-03-16T13:00:00Z',
    'Status': 'Active',
    'Notes': '[2026-03-18 10:30] Call completed. 5% down conventional. Submitted pre-approval application. Awaiting income docs.',
  },

  // ── 23. Ryan Henderson — CA — COLD ──────────────────────────────────────────
  {
    rowNumber: 24,
    'Date': '2026-03-03',
    'First Name': 'Ryan',
    'Last Name': 'Henderson',
    'Email': 'ryan.henderson@gmail.com',
    'Phone': '(949) 712-5083',
    'Zip Code': '92651',
    'State': 'CA',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '600-619',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Loan Balance': '398000',
    'Property Value': '615000',
    'Rate Type': 'Fixed',
    'Annual Income': '115000',
    'Employment Status': 'Self-Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Website',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-03',
    'Time Submitted': '05:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-03T17:00:00Z',
    'Status': 'Cold',
    'Notes': '[2026-03-20 09:00] Three unanswered follow-ups. Credit score concern flagged. Moving to cold — revisit in 90 days after credit repair.\n[2026-03-05 09:00] Left voicemail and email. Refi may be difficult at current score.',
  },

  // ── 24. Michelle Kim — FL — IN PROGRESS ─────────────────────────────────────
  {
    rowNumber: 25,
    'Date': '2026-02-25',
    'First Name': 'Michelle',
    'Last Name': 'Kim',
    'Email': 'michelle.kim@gmail.com',
    'Phone': '(407) 883-6120',
    'Zip Code': '32801',
    'State': 'FL',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '740-759',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '425000',
    'Down Payment': '85000',
    'Rate Type': 'Fixed',
    'Annual Income': '118000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'LeadPops AZ Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/home-purchase',
    'Date Submitted': '2026-02-25',
    'Time Submitted': '10:45 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-02-25T10:45:00Z',
    'Status': 'In Progress',
    'Notes': '[2026-03-24 11:00] Appraisal complete at $432k. File in underwriting. Closing set for 4/8.\n[2026-03-05 09:30] Pre-approval issued. Under contract on Orlando SFH. Docs submitted.',
  },

  // ── 25. Tyler Washington — NV — LOST ────────────────────────────────────────
  {
    rowNumber: 26,
    'Date': '2026-02-28',
    'First Name': 'Tyler',
    'Last Name': 'Washington',
    'Email': 'tyler.washington@gmail.com',
    'Phone': '(702) 265-7483',
    'Zip Code': '89117',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '580-599',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 1-3 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '355000',
    'Down Payment': '12425',
    'Rate Type': 'Fixed',
    'Annual Income': '62000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate NV Purchase',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-02-28',
    'Time Submitted': '08:30 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-02-28T08:30:00Z',
    'Status': 'Lost',
    'Notes': '[2026-03-18 09:00] Tyler went with a credit repair company instead. Needs 6-12 months to improve score. Marked lost — add to long-term drip.\n[2026-03-03 09:00] Call completed. 580 FICO — below FHA minimum. Advised credit repair path.',
  },
]

// Helper: get full name from a lead object
export function getFullName(lead) {
  const first = lead['First Name'] || ''
  const last = lead['Last Name'] || ''
  return `${first} ${last}`.trim()
}
