// 25 demo leads for Nick Flores Sr. — Team Flores CRM
// Covers all 8 stages, multiple states (NV/AZ/CA/FL/TX), multiple sources
// rowNumber 2–26

export const MOCK_LEADS = [
  // ── 1. Maria Garcia — NV — CONTACTED ────────────────────────────────────────
  {
    rowNumber: 2,
    'Date': '2026-03-21',
    'First Name': 'Maria',
    'Last Name': 'Garcia',
    'Email': 'maria.garcia@gmail.com',
    'Phone': '(702) 318-4521',
    'Zip Code': '89117',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '435000',
    'Down Payment': '87000',
    'Rate Type': 'Fixed',
    'Annual Income': '120000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'LeadPops NV Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/home-purchase',
    'Date Submitted': '2026-03-21',
    'Time Submitted': '02:30 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-21T14:30:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-03-22 09:05] Text sent using LeadPops NV Purchase template. Email intro sent. Awaiting response.',
  },

  // ── 2. James Wilson — AZ — QUALIFIED ────────────────────────────────────────
  {
    rowNumber: 3,
    'Date': '2026-03-10',
    'First Name': 'James',
    'Last Name': 'Wilson',
    'Email': 'james.wilson@gmail.com',
    'Phone': '(480) 445-7832',
    'Zip Code': '85251',
    'State': 'AZ',
    'Loan Type': 'VA Loan',
    'VA Loan': 'Yes',
    'Property Type': 'Single Family',
    'Credit Score': '700-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '395000',
    'Down Payment': '0',
    'Rate Type': 'Fixed',
    'Annual Income': '92000',
    'Employment Status': 'Veteran',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-10',
    'Time Submitted': '10:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-10T10:00:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-03-20 10:00] VA certificate of eligibility received. Pre-approval letter issued. Reviewing properties in Scottsdale.\n[2026-03-12 10:30] Call completed. Veteran using VA benefit for first home. Very motivated.',
  },

  // ── 3. Sarah Johnson — NV — CLOSED WON ──────────────────────────────────────
  {
    rowNumber: 4,
    'Date': '2026-02-01',
    'First Name': 'Sarah',
    'Last Name': 'Johnson',
    'Email': 'sarah.johnson@gmail.com',
    'Phone': '(702) 562-9043',
    'Zip Code': '89134',
    'State': 'NV',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '480000',
    'Down Payment': '96000',
    'Loan Balance': '310000',
    'Property Value': '520000',
    'Rate Type': 'Fixed',
    'Annual Income': '148000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate NV Refi',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-02-01',
    'Time Submitted': '03:00 PM',
    'Browser': 'Safari',
    'Submitted At': '2026-02-01T15:00:00Z',
    'Status': 'Closed Won',
    'Notes': '[2026-03-14 15:00] LOAN FUNDED! Sarah refinanced her primary residence in Summerlin. Lowered rate by 1.2%. Monthly savings $415/mo. Excellent client — referred two coworkers.\n[2026-02-05 10:00] Initial disclosures sent.\n[2026-02-03 09:00] Call completed. Very interested in refinancing to lower rate.',
  },

  // ── 4. Robert Martinez — TX — NEW ───────────────────────────────────────────
  {
    rowNumber: 5,
    'Date': '2026-03-28',
    'First Name': 'Robert',
    'Last Name': 'Martinez',
    'Email': 'robert.martinez@gmail.com',
    'Phone': '(214) 234-6780',
    'Zip Code': '75201',
    'State': 'TX',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '680-699',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '355000',
    'Down Payment': '17750',
    'Rate Type': 'Fixed',
    'Annual Income': '82000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate TX Purchase',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-28',
    'Time Submitted': '09:15 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-28T09:15:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 5. Jennifer Davis — NV — ACTIVE ─────────────────────────────────────────
  {
    rowNumber: 6,
    'Date': '2026-03-23',
    'First Name': 'Jennifer',
    'Last Name': 'Davis',
    'Email': 'jennifer.davis@gmail.com',
    'Phone': '(702) 891-2354',
    'Zip Code': '89119',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '720-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '385000',
    'Down Payment': '77000',
    'Rate Type': 'Fixed',
    'Annual Income': '108000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-23',
    'Time Submitted': '11:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-23T11:00:00Z',
    'Status': 'Active',
    'Notes': '[2026-03-25 02:30 PM] Jennifer texted back: "Hi Nick! Yes I am interested. Can we talk tomorrow morning?" — REPLIED.\n[2026-03-23 11:15 AM] Intro text sent using Zillow template. Email sent.',
  },

  // ── 6. Michael Brown — NV — IN PROGRESS ─────────────────────────────────────
  {
    rowNumber: 7,
    'Date': '2026-03-05',
    'First Name': 'Michael',
    'Last Name': 'Brown',
    'Email': 'michael.brown@gmail.com',
    'Phone': '(702) 677-5129',
    'Zip Code': '89144',
    'State': 'NV',
    'Loan Type': 'VA Loan',
    'VA Loan': 'Yes',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '450000',
    'Down Payment': '0',
    'Rate Type': 'Fixed',
    'Annual Income': '125000',
    'Employment Status': 'Veteran',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'LeadPops NV Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/va-loan',
    'Date Submitted': '2026-03-05',
    'Time Submitted': '02:00 PM',
    'Browser': 'Edge',
    'Submitted At': '2026-03-05T14:00:00Z',
    'Status': 'In Progress',
    'Notes': '[2026-03-26 10:00] Sonar application submitted. Awaiting underwriting decision.\n[2026-03-18 10:00] Pre-approval letter issued. Documents submitted.\n[2026-03-08 10:00] Call completed. Strong VA candidate. Excellent credit and income.',
  },

  // ── 7. Lisa Anderson — CA — NEW ─────────────────────────────────────────────
  {
    rowNumber: 8,
    'Date': '2026-03-28',
    'First Name': 'Lisa',
    'Last Name': 'Anderson',
    'Email': 'lisa.anderson@gmail.com',
    'Phone': '(818) 345-8912',
    'Zip Code': '91601',
    'State': 'CA',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Condo',
    'Credit Score': '680-699',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 1-3 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '650000',
    'Down Payment': '130000',
    'Rate Type': 'Fixed',
    'Annual Income': '128000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate CA Purchase',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-28',
    'Time Submitted': '07:45 AM',
    'Browser': 'Firefox',
    'Submitted At': '2026-03-28T07:45:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 8. David Taylor — NV — CLOSED WON ───────────────────────────────────────
  {
    rowNumber: 9,
    'Date': '2026-01-15',
    'First Name': 'David',
    'Last Name': 'Taylor',
    'Email': 'david.taylor@gmail.com',
    'Phone': '(702) 718-4307',
    'Zip Code': '89141',
    'State': 'NV',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '720-739',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '525000',
    'Down Payment': '105000',
    'Loan Balance': '390000',
    'Property Value': '560000',
    'Rate Type': 'Fixed',
    'Annual Income': '152000',
    'Employment Status': 'Self-Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Sunnyhill Past Client Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-01-15',
    'Time Submitted': '03:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-01-15T15:00:00Z',
    'Status': 'Closed Won',
    'Notes': '[2026-03-02 15:00] LOAN FUNDED! David refinanced his home and lowered monthly payment by $420/mo. Self-employed docs were thorough and clean.\n[2026-01-20 10:00] Call completed. Self-employed business owner, excellent documentation.',
  },

  // ── 9. Ashley Thomas — NV — CONTACTED ───────────────────────────────────────
  {
    rowNumber: 10,
    'Date': '2026-03-24',
    'First Name': 'Ashley',
    'Last Name': 'Thomas',
    'Email': 'ashley.thomas@gmail.com',
    'Phone': '(702) 523-6741',
    'Zip Code': '89138',
    'State': 'NV',
    'Loan Type': 'Conv Hybrid',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '595000',
    'Down Payment': '119000',
    'Rate Type': 'Adjustable',
    'Annual Income': '168000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Realtor Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-24',
    'Time Submitted': '04:00 PM',
    'Browser': 'Safari',
    'Submitted At': '2026-03-24T16:00:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-03-24 04:15 PM] Intro text and email sent. Realtor is Rachel Gomez. High-value purchase, move-up buyer.',
  },

  // ── 10. Christopher Jackson — FL — DEAD ─────────────────────────────────────
  {
    rowNumber: 11,
    'Date': '2026-02-15',
    'First Name': 'Christopher',
    'Last Name': 'Jackson',
    'Email': 'christopher.jackson@gmail.com',
    'Phone': '(305) 489-2163',
    'Zip Code': '33101',
    'State': 'FL',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '620-659',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 1-3 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '410000',
    'Down Payment': '20500',
    'Rate Type': 'Fixed',
    'Annual Income': '78000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate FL Purchase',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-02-15',
    'Time Submitted': '10:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-02-15T10:00:00Z',
    'Status': 'Dead',
    'Notes': '[2026-03-18 09:30] Cold sequence exhausted. 31 days, no reply. Marking Dead.\n[2026-03-10 08:00] Day 21 text — no reply.\n[2026-03-03 08:00] Day 14 email — no reply.\n[2026-02-22 08:00] Day 7 text — no reply.\n[2026-02-18 08:00] Day 3 email — no reply.\n[2026-02-16 10:05] Intro text sent.',
  },

  // ── 11. Amanda White — NV — QUALIFIED ───────────────────────────────────────
  {
    rowNumber: 12,
    'Date': '2026-03-12',
    'First Name': 'Amanda',
    'Last Name': 'White',
    'Email': 'amanda.white@gmail.com',
    'Phone': '(702) 834-5627',
    'Zip Code': '89146',
    'State': 'NV',
    'Loan Type': 'VA Loan',
    'VA Loan': 'Yes',
    'Property Type': 'Single Family',
    'Credit Score': '700-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '410000',
    'Down Payment': '0',
    'Rate Type': 'Fixed',
    'Annual Income': '95000',
    'Employment Status': 'Military',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'LeadPops NV Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/va-military',
    'Date Submitted': '2026-03-12',
    'Time Submitted': '11:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-12T11:00:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-03-24 10:00] COE received. VA appraisal ordered. Pre-approval letter issued at $410k.\n[2026-03-15 10:30] Call completed. Active military purchasing primary residence. Excited to buy!',
  },

  // ── 12. Matthew Harris — NV — NEW ───────────────────────────────────────────
  {
    rowNumber: 13,
    'Date': '2026-03-28',
    'First Name': 'Matthew',
    'Last Name': 'Harris',
    'Email': 'matthew.harris@gmail.com',
    'Phone': '(702) 267-9834',
    'Zip Code': '89103',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '485000',
    'Down Payment': '97000',
    'Rate Type': 'Fixed',
    'Annual Income': '145000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/purchase',
    'Date Submitted': '2026-03-28',
    'Time Submitted': '08:45 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-28T08:45:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 13. Stephanie Martin — NV — COLD ────────────────────────────────────────
  {
    rowNumber: 14,
    'Date': '2026-03-01',
    'First Name': 'Stephanie',
    'Last Name': 'Martin',
    'Email': 'stephanie.martin@gmail.com',
    'Phone': '(702) 614-3782',
    'Zip Code': '89128',
    'State': 'NV',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '700-739',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '440000',
    'Down Payment': '88000',
    'Loan Balance': '295000',
    'Property Value': '460000',
    'Rate Type': 'Fixed',
    'Annual Income': '118000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate NV Refi',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/refinance',
    'Date Submitted': '2026-03-01',
    'Time Submitted': '10:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-01T10:00:00Z',
    'Status': 'Cold',
    'Notes': '[2026-03-22 09:00] Auto-moved to Cold: no contact for 21 days. Cold sequence started.\n[2026-03-04 08:00] Day 3 email sent.\n[2026-03-01 10:05] Intro text sent. No reply.',
  },

  // ── 14. Joshua Thompson — NV — IN PROGRESS ──────────────────────────────────
  {
    rowNumber: 15,
    'Date': '2026-03-08',
    'First Name': 'Joshua',
    'Last Name': 'Thompson',
    'Email': 'joshua.thompson@gmail.com',
    'Phone': '(702) 789-4523',
    'Zip Code': '89117',
    'State': 'NV',
    'Loan Type': 'HELOC/Equity',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '720-739',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '580000',
    'Down Payment': '0',
    'Loan Balance': '320000',
    'Property Value': '595000',
    'Rate Type': 'Fixed',
    'Annual Income': '140000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate NV Refi',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-08',
    'Time Submitted': '03:00 PM',
    'Browser': 'Firefox',
    'Submitted At': '2026-03-08T15:00:00Z',
    'Status': 'In Progress',
    'Notes': '[2026-03-25 10:00] Sonar HELOC application submitted. Appraisal ordered. Underwriting review pending.\n[2026-03-18 10:00] Pre-approval for HELOC issued.\n[2026-03-11 10:00] Call completed. Accessing equity for kitchen remodel + ADU.',
  },

  // ── 15. Megan Garcia — NV — CLOSED WON ──────────────────────────────────────
  {
    rowNumber: 16,
    'Date': '2026-02-10',
    'First Name': 'Megan',
    'Last Name': 'Garcia',
    'Email': 'megan.garcia@gmail.com',
    'Phone': '(702) 351-8076',
    'Zip Code': '89134',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '780-799',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '545000',
    'Down Payment': '109000',
    'Rate Type': 'Fixed',
    'Annual Income': '162000',
    'Employment Status': 'Self-Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Realtor Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-02-10',
    'Time Submitted': '04:00 PM',
    'Browser': 'Safari',
    'Submitted At': '2026-02-10T16:00:00Z',
    'Status': 'Closed Won',
    'Notes': '[2026-03-20 16:00] LOAN FUNDED! Megan purchased SFH in Summerlin. First-time buyer — made the process stress-free. Already referred her sister.\n[2026-02-14 10:30] Call completed. Self-employed 3 years, strong income docs.',
  },

  // ── 16. Andrew Martinez — NV — NEW ──────────────────────────────────────────
  {
    rowNumber: 17,
    'Date': '2026-03-27',
    'First Name': 'Andrew',
    'Last Name': 'Martinez',
    'Email': 'andrew.martinez@gmail.com',
    'Phone': '(702) 412-5938',
    'Zip Code': '89101',
    'State': 'NV',
    'Loan Type': 'VA Loan',
    'VA Loan': 'Yes',
    'Property Type': 'Single Family',
    'Credit Score': '680-699',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 1-3 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '345000',
    'Down Payment': '0',
    'Rate Type': 'Fixed',
    'Annual Income': '72000',
    'Employment Status': 'Veteran',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'LeadPops NV Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/va-loan',
    'Date Submitted': '2026-03-27',
    'Time Submitted': '04:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-27T16:00:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 17. Lauren Robinson — NV — ACTIVE ───────────────────────────────────────
  {
    rowNumber: 18,
    'Date': '2026-03-26',
    'First Name': 'Lauren',
    'Last Name': 'Robinson',
    'Email': 'lauren.robinson@gmail.com',
    'Phone': '(702) 956-2847',
    'Zip Code': '89119',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Townhouse',
    'Credit Score': '700-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '400000',
    'Down Payment': '80000',
    'Rate Type': 'Fixed',
    'Annual Income': '105000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-26',
    'Time Submitted': '02:30 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-26T14:30:00Z',
    'Status': 'Active',
    'Notes': '[2026-03-27 11:00 AM] Lauren replied: "Yes! Can we schedule a call for this afternoon?" — HOT LEAD.\n[2026-03-26 02:45 PM] Intro text sent using Zillow template.',
  },

  // ── 18. Ryan Clark — NV — QUALIFIED ─────────────────────────────────────────
  {
    rowNumber: 19,
    'Date': '2026-03-18',
    'First Name': 'Ryan',
    'Last Name': 'Clark',
    'Email': 'ryan.clark@gmail.com',
    'Phone': '(702) 723-4819',
    'Zip Code': '89144',
    'State': 'NV',
    'Loan Type': 'Conv Hybrid',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '625000',
    'Down Payment': '125000',
    'Rate Type': 'Adjustable',
    'Annual Income': '195000',
    'Employment Status': 'Self-Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Realtor Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-18',
    'Time Submitted': '10:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-18T10:00:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-03-24 10:35] Pre-approval issued at $625k. Moving forward with 5/1 ARM. Strong self-employed file.\n[2026-03-20 09:00] Call completed. 5/1 ARM makes sense for 5-year plan.',
  },

  // ── 19. Brittany Rodriguez — NV — NEW ───────────────────────────────────────
  {
    rowNumber: 20,
    'Date': '2026-03-28',
    'First Name': 'Brittany',
    'Last Name': 'Rodriguez',
    'Email': 'brittany.rodriguez@gmail.com',
    'Phone': '(702) 381-7264',
    'Zip Code': '89102',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Condo',
    'Credit Score': '680-699',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 1-3 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '310000',
    'Down Payment': '15500',
    'Rate Type': 'Fixed',
    'Annual Income': '76000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'LeadPops NV Purchase',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-28',
    'Time Submitted': '06:30 AM',
    'Browser': 'Firefox',
    'Submitted At': '2026-03-28T06:30:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 20. Kevin Lewis — NV — CLOSED WON ───────────────────────────────────────
  {
    rowNumber: 21,
    'Date': '2026-01-20',
    'First Name': 'Kevin',
    'Last Name': 'Lewis',
    'Email': 'kevin.lewis@gmail.com',
    'Phone': '(702) 547-9321',
    'Zip Code': '89141',
    'State': 'NV',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '720-739',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '465000',
    'Down Payment': '93000',
    'Loan Balance': '310000',
    'Property Value': '490000',
    'Rate Type': 'Fixed',
    'Annual Income': '128000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Sunnyhill Past Client Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-01-20',
    'Time Submitted': '03:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-01-20T15:00:00Z',
    'Status': 'Closed Won',
    'Notes': '[2026-03-05 15:00] LOAN FUNDED! Kevin refinanced and lowered payment by $380/mo. Has already referred a neighbor.\n[2026-01-23 10:00] Call completed. Looking to reduce monthly payment. Great profile.',
  },

  // ── 21. Samantha Lee — NV — COLD ────────────────────────────────────────────
  {
    rowNumber: 22,
    'Date': '2026-03-01',
    'First Name': 'Samantha',
    'Last Name': 'Lee',
    'Email': 'samantha.lee@gmail.com',
    'Phone': '(702) 829-4615',
    'Zip Code': '89138',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '510000',
    'Down Payment': '102000',
    'Rate Type': 'Fixed',
    'Annual Income': '148000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'LeadPops NV Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/purchase',
    'Date Submitted': '2026-03-01',
    'Time Submitted': '03:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-01T15:00:00Z',
    'Status': 'Cold',
    'Notes': '[2026-03-22 09:00] Auto-moved to Cold: 21 days no contact. Cold sequence step 2 running.\n[2026-03-04 08:00] Day 3 email sent — no reply.\n[2026-03-01 03:15 PM] Intro text sent. No reply.',
  },

  // ── 22. Tyler Walker — NV — QUALIFIED ───────────────────────────────────────
  {
    rowNumber: 23,
    'Date': '2026-03-15',
    'First Name': 'Tyler',
    'Last Name': 'Walker',
    'Email': 'tyler.walker@gmail.com',
    'Phone': '(702) 634-8172',
    'Zip Code': '89128',
    'State': 'NV',
    'Loan Type': 'VA Loan',
    'VA Loan': 'Yes',
    'Property Type': 'Single Family',
    'Credit Score': '720-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '420000',
    'Down Payment': '0',
    'Rate Type': 'Fixed',
    'Annual Income': '98000',
    'Employment Status': 'Veteran',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'LeadPops NV Purchase',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/va-loan',
    'Date Submitted': '2026-03-15',
    'Time Submitted': '09:15 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-15T09:15:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-03-24 09:15] VA pre-approval letter issued at $420k. COE verified. Touring homes this weekend.\n[2026-03-17 02:00 PM] Call completed. Veteran, first VA loan, very excited.',
  },

  // ── 23. Nicole Hall — TX — NEW ───────────────────────────────────────────────
  {
    rowNumber: 24,
    'Date': '2026-03-28',
    'First Name': 'Nicole',
    'Last Name': 'Hall',
    'Email': 'nicole.hall@gmail.com',
    'Phone': '(512) 472-3895',
    'Zip Code': '78701',
    'State': 'TX',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '700-739',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '420000',
    'Down Payment': '0',
    'Loan Balance': '290000',
    'Property Value': '435000',
    'Rate Type': 'Fixed',
    'Annual Income': '95000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'LeadPops TX Refi',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-28',
    'Time Submitted': '05:15 AM',
    'Browser': 'Safari',
    'Submitted At': '2026-03-28T05:15:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 24. Brandon Allen — NV — CLOSED WON ─────────────────────────────────────
  {
    rowNumber: 25,
    'Date': '2026-01-25',
    'First Name': 'Brandon',
    'Last Name': 'Allen',
    'Email': 'brandon.allen@gmail.com',
    'Phone': '(702) 918-6347',
    'Zip Code': '89134',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '780-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '580000',
    'Down Payment': '116000',
    'Rate Type': 'Fixed',
    'Annual Income': '175000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/purchase',
    'Date Submitted': '2026-01-25',
    'Time Submitted': '04:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-01-25T16:00:00Z',
    'Status': 'Closed Won',
    'Notes': '[2026-03-10 04:00 PM] LOAN FUNDED! Brandon purchased SFH in Summerlin $580k. Smooth, fast transaction. Referred two colleagues already.\n[2026-01-28 11:00] Call completed. Strong income and assets. Ready to buy immediately.',
  },

  // ── 25. Kayla Young — NV — ACTIVE ───────────────────────────────────────────
  {
    rowNumber: 26,
    'Date': '2026-03-27',
    'First Name': 'Kayla',
    'Last Name': 'Young',
    'Email': 'kayla.young@gmail.com',
    'Phone': '(702) 265-7483',
    'Zip Code': '89117',
    'State': 'NV',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '700-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '385000',
    'Down Payment': '77000',
    'Rate Type': 'Fixed',
    'Annual Income': '96000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Realtor Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-27',
    'Time Submitted': '08:30 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-27T08:30:00Z',
    'Status': 'Active',
    'Notes': '[2026-03-27 10:15 AM] Kayla called back! Great conversation. Pre-approval process explained. Sending Sonar link.\n[2026-03-27 08:45 AM] Intro text sent. Kayla replied within 20 minutes.',
  },
]

// Helper: get full name from a lead object
export function getFullName(lead) {
  const first = lead['First Name'] || ''
  const last = lead['Last Name'] || ''
  return `${first} ${last}`.trim()
}
