// 25 demo leads for Nick Flores — Team Flores CRM
// rowNumber 2–26, spread over last 90 days

export const MOCK_LEADS = [
  // ── 1. Maria Garcia ── Contacted ───────────────────────────────────────────
  {
    rowNumber: 2,
    'Date': '2026-02-15',
    'First Name': 'Maria',
    'Last Name': 'Garcia',
    'Email': 'maria.garcia@gmail.com',
    'Phone': '(702) 318-4521',
    'Zip Code': '89117',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '435000',
    'Down Payment': '87000',
    'Rate Type': 'Fixed',
    'Annual Income': '120000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Google',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/home-purchase',
    'Date Submitted': '2026-02-15',
    'Time Submitted': '02:30 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-02-15T14:30:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-02-16 09:05] Email sent. Follow-up text sent 2/18. Awaiting response.',
  },

  // ── 2. James Wilson ── Qualified ───────────────────────────────────────────
  {
    rowNumber: 3,
    'Date': '2026-02-01',
    'First Name': 'James',
    'Last Name': 'Wilson',
    'Email': 'james.wilson@gmail.com',
    'Phone': '(702) 445-7832',
    'Zip Code': '89128',
    'Loan Type': 'VA Loan',
    'VA Loan': 'Yes',
    'Property Type': 'Single Family',
    'Credit Score': '700-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '395000',
    'Down Payment': '0',
    'Rate Type': 'Fixed',
    'Annual Income': '92000',
    'Employment Status': 'Veteran',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-02-01',
    'Time Submitted': '10:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-02-01T10:00:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-02-14 10:00] VA certificate of eligibility received. Gathering remaining docs.\n[2026-02-05 10:30] Call completed. Veteran using VA benefit for first home. Very motivated.',
  },

  // ── 3. Sarah Johnson ── Closed ─────────────────────────────────────────────
  {
    rowNumber: 4,
    'Date': '2026-03-02',
    'First Name': 'Sarah',
    'Last Name': 'Johnson',
    'Email': 'sarah.johnson@gmail.com',
    'Phone': '(702) 562-9043',
    'Zip Code': '89134',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '480000',
    'Down Payment': '96000',
    'Rate Type': 'Fixed',
    'Annual Income': '148000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Sunnyhill Past Client Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-02',
    'Time Submitted': '03:00 PM',
    'Browser': 'Safari',
    'Submitted At': '2026-03-02T15:00:00Z',
    'Status': 'Closed',
    'Notes': '[2026-03-02 15:00] Loan funded. Sarah refinanced her primary residence in Summerlin. Lowered rate by 1.2%. Excellent client — referred two coworkers.\n[2025-12-23 10:00] Call completed. Very interested in refinancing to lower rate.',
  },

  // ── 4. Robert Martinez ── New ──────────────────────────────────────────────
  {
    rowNumber: 5,
    'Date': '2026-03-10',
    'First Name': 'Robert',
    'Last Name': 'Martinez',
    'Email': 'robert.martinez@gmail.com',
    'Phone': '(702) 234-6780',
    'Zip Code': '89101',
    'Loan Type': 'HELOC/Equity',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '660-699',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '355000',
    'Down Payment': '35500',
    'Rate Type': 'Fixed',
    'Annual Income': '82000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Google',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/heloc',
    'Date Submitted': '2026-03-10',
    'Time Submitted': '02:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-10T14:00:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 5. Jennifer Davis ── Contacted ─────────────────────────────────────────
  {
    rowNumber: 6,
    'Date': '2026-02-20',
    'First Name': 'Jennifer',
    'Last Name': 'Davis',
    'Email': 'jennifer.davis@gmail.com',
    'Phone': '(702) 891-2354',
    'Zip Code': '89119',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '720-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '385000',
    'Down Payment': '77000',
    'Rate Type': 'Fixed',
    'Annual Income': '108000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-02-20',
    'Time Submitted': '11:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-02-20T11:00:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-02-21 09:35] Intro email sent. Follow-up text sent 2/23. Interested in 4BR home.',
  },

  // ── 6. Michael Brown ── Qualified ──────────────────────────────────────────
  {
    rowNumber: 7,
    'Date': '2026-02-05',
    'First Name': 'Michael',
    'Last Name': 'Brown',
    'Email': 'michael.brown@gmail.com',
    'Phone': '(702) 677-5129',
    'Zip Code': '89144',
    'Loan Type': 'VA Loan',
    'VA Loan': 'Yes',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '450000',
    'Down Payment': '0',
    'Rate Type': 'Fixed',
    'Annual Income': '125000',
    'Employment Status': 'Veteran',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Google',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/va-loan',
    'Date Submitted': '2026-02-05',
    'Time Submitted': '02:00 PM',
    'Browser': 'Edge',
    'Submitted At': '2026-02-05T14:00:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-02-18 10:00] Documents submitted. Pre-approval letter issued.\n[2026-02-08 10:00] Call completed. Strong VA candidate. Excellent credit and income.',
  },

  // ── 7. Lisa Anderson ── New ────────────────────────────────────────────────
  {
    rowNumber: 8,
    'Date': '2026-03-08',
    'First Name': 'Lisa',
    'Last Name': 'Anderson',
    'Email': 'lisa.anderson@gmail.com',
    'Phone': '(702) 345-8912',
    'Zip Code': '89102',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Condo',
    'Credit Score': '620-659',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 1-3 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '275000',
    'Down Payment': '9625',
    'Rate Type': 'Fixed',
    'Annual Income': '58000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Social Media',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-08',
    'Time Submitted': '11:30 AM',
    'Browser': 'Firefox',
    'Submitted At': '2026-03-08T11:30:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 8. David Taylor ── Closed ──────────────────────────────────────────────
  {
    rowNumber: 9,
    'Date': '2026-02-25',
    'First Name': 'David',
    'Last Name': 'Taylor',
    'Email': 'david.taylor@gmail.com',
    'Phone': '(702) 718-4307',
    'Zip Code': '89141',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '720-739',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '525000',
    'Down Payment': '105000',
    'Rate Type': 'Fixed',
    'Annual Income': '152000',
    'Employment Status': 'Self-Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Sunnyhill Past Client Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-02-25',
    'Time Submitted': '03:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-02-25T15:00:00Z',
    'Status': 'Closed',
    'Notes': '[2026-02-25 15:00] Loan funded. David refinanced his home and lowered monthly payment by $420/mo. Self-employed docs were thorough and clean.\n[2026-01-02 10:00] Call completed. Self-employed business owner, excellent documentation.',
  },

  // ── 9. Ashley Thomas ── Contacted ─────────────────────────────────────────
  {
    rowNumber: 10,
    'Date': '2026-02-25',
    'First Name': 'Ashley',
    'Last Name': 'Thomas',
    'Email': 'ashley.thomas@gmail.com',
    'Phone': '(702) 523-6741',
    'Zip Code': '89138',
    'Loan Type': 'Conv Hybrid',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '595000',
    'Down Payment': '119000',
    'Rate Type': 'Adjustable',
    'Annual Income': '168000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Realtor Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-02-25',
    'Time Submitted': '04:00 PM',
    'Browser': 'Safari',
    'Submitted At': '2026-02-25T16:00:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-02-26 09:05] Intro email sent. Interested in 5/1 ARM for move-up purchase.',
  },

  // ── 10. Christopher Jackson ── Lost ────────────────────────────────────────
  {
    rowNumber: 11,
    'Date': '2026-01-15',
    'First Name': 'Christopher',
    'Last Name': 'Jackson',
    'Email': 'christopher.jackson@gmail.com',
    'Phone': '(702) 489-2163',
    'Zip Code': '89109',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '660-699',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 1-3 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '320000',
    'Down Payment': '16000',
    'Rate Type': 'Fixed',
    'Annual Income': '78000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-01-15',
    'Time Submitted': '10:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-01-15T10:00:00Z',
    'Status': 'Lost',
    'Notes': '[2026-02-05 09:30] Lead went with another lender. Was comparison shopping and found a lower advertised rate online. Followed up twice but no response. Marking lost.',
  },

  // ── 11. Amanda White ── Qualified ──────────────────────────────────────────
  {
    rowNumber: 12,
    'Date': '2026-02-10',
    'First Name': 'Amanda',
    'Last Name': 'White',
    'Email': 'amanda.white@gmail.com',
    'Phone': '(702) 834-5627',
    'Zip Code': '89146',
    'Loan Type': 'VA Loan',
    'VA Loan': 'Yes',
    'Property Type': 'Single Family',
    'Credit Score': '700-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '410000',
    'Down Payment': '0',
    'Rate Type': 'Fixed',
    'Annual Income': '95000',
    'Employment Status': 'Military',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Google',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/va-military',
    'Date Submitted': '2026-02-10',
    'Time Submitted': '11:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-02-10T11:00:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-02-22 10:00] COE received. VA appraisal ordered. Pre-approval letter issued.\n[2026-02-13 10:30] Call completed. Active military purchasing primary residence. Excited!',
  },

  // ── 12. Matthew Harris ── New (submitted today) ────────────────────────────
  {
    rowNumber: 13,
    'Date': '2026-03-16',
    'First Name': 'Matthew',
    'Last Name': 'Harris',
    'Email': 'matthew.harris@gmail.com',
    'Phone': '(702) 267-9834',
    'Zip Code': '89103',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '485000',
    'Down Payment': '97000',
    'Rate Type': 'Fixed',
    'Annual Income': '145000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/purchase',
    'Date Submitted': '2026-03-16',
    'Time Submitted': '10:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-16T10:00:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 13. Stephanie Martin ── Contacted ──────────────────────────────────────
  {
    rowNumber: 14,
    'Date': '2026-03-01',
    'First Name': 'Stephanie',
    'Last Name': 'Martin',
    'Email': 'stephanie.martin@gmail.com',
    'Phone': '(702) 614-3782',
    'Zip Code': '89128',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '700-739',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '440000',
    'Down Payment': '88000',
    'Rate Type': 'Fixed',
    'Annual Income': '118000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Google',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/refinance',
    'Date Submitted': '2026-03-01',
    'Time Submitted': '10:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-01T10:00:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-03-02 09:05] Intro email sent. Follow-up text sent 3/4. Awaiting response on refinance inquiry.',
  },

  // ── 14. Joshua Thompson ── Qualified ───────────────────────────────────────
  {
    rowNumber: 15,
    'Date': '2026-02-18',
    'First Name': 'Joshua',
    'Last Name': 'Thompson',
    'Email': 'joshua.thompson@gmail.com',
    'Phone': '(702) 789-4523',
    'Zip Code': '89117',
    'Loan Type': 'HELOC/Equity',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '660-699',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '390000',
    'Down Payment': '39000',
    'Rate Type': 'Fixed',
    'Annual Income': '88000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-02-18',
    'Time Submitted': '03:00 PM',
    'Browser': 'Firefox',
    'Submitted At': '2026-02-18T15:00:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-03-02 10:00] HELOC application submitted. Appraisal ordered.\n[2026-02-21 10:00] Call completed. Accessing equity for kitchen remodel and ADU addition.',
  },

  // ── 15. Megan Garcia ── Closed ─────────────────────────────────────────────
  {
    rowNumber: 16,
    'Date': '2026-03-05',
    'First Name': 'Megan',
    'Last Name': 'Garcia',
    'Email': 'megan.garcia@gmail.com',
    'Phone': '(702) 351-8076',
    'Zip Code': '89134',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '780-799',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '545000',
    'Down Payment': '109000',
    'Rate Type': 'Fixed',
    'Annual Income': '162000',
    'Employment Status': 'Self-Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Realtor Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-05',
    'Time Submitted': '04:00 PM',
    'Browser': 'Safari',
    'Submitted At': '2026-03-05T16:00:00Z',
    'Status': 'Closed',
    'Notes': '[2026-03-05 16:00] Loan funded. Megan purchased a single family home in Summerlin. First-time buyer — made the whole process stress-free. Will definitely refer.\n[2026-01-08 10:30] Call completed. Self-employed 3 years, strong income docs.',
  },

  // ── 16. Andrew Martinez ── New ─────────────────────────────────────────────
  {
    rowNumber: 17,
    'Date': '2026-03-10',
    'First Name': 'Andrew',
    'Last Name': 'Martinez',
    'Email': 'andrew.martinez@gmail.com',
    'Phone': '(702) 412-5938',
    'Zip Code': '89101',
    'Loan Type': 'VA Loan',
    'VA Loan': 'Yes',
    'Property Type': 'Single Family',
    'Credit Score': '620-659',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 1-3 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '345000',
    'Down Payment': '0',
    'Rate Type': 'Fixed',
    'Annual Income': '72000',
    'Employment Status': 'Veteran',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Google',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/va-loan',
    'Date Submitted': '2026-03-10',
    'Time Submitted': '04:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-10T16:00:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 17. Lauren Robinson ── Contacted (yesterday) ───────────────────────────
  {
    rowNumber: 18,
    'Date': '2026-03-15',
    'First Name': 'Lauren',
    'Last Name': 'Robinson',
    'Email': 'lauren.robinson@gmail.com',
    'Phone': '(702) 956-2847',
    'Zip Code': '89119',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Townhouse',
    'Credit Score': '700-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '400000',
    'Down Payment': '80000',
    'Rate Type': 'Fixed',
    'Annual Income': '105000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-15',
    'Time Submitted': '02:30 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-15T14:30:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-03-15 04:05 PM] Intro email sent. Follow-up text sent this morning. Hot lead.',
  },

  // ── 18. Ryan Clark ── Qualified (yesterday) ────────────────────────────────
  {
    rowNumber: 19,
    'Date': '2026-03-15',
    'First Name': 'Ryan',
    'Last Name': 'Clark',
    'Email': 'ryan.clark@gmail.com',
    'Phone': '(702) 723-4819',
    'Zip Code': '89144',
    'Loan Type': 'Conv Hybrid',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '625000',
    'Down Payment': '125000',
    'Rate Type': 'Adjustable',
    'Annual Income': '195000',
    'Employment Status': 'Self-Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Realtor Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-15',
    'Time Submitted': '10:00 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-15T10:00:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-03-16 10:35] Pre-approval issued. Moving forward with ARM. Strong self-employed file.\n[2026-03-16 09:00] Call completed. 5/1 ARM makes sense for his 5-year plan. Excellent income.',
  },

  // ── 19. Brittany Rodriguez ── New ──────────────────────────────────────────
  {
    rowNumber: 20,
    'Date': '2026-03-11',
    'First Name': 'Brittany',
    'Last Name': 'Rodriguez',
    'Email': 'brittany.rodriguez@gmail.com',
    'Phone': '(702) 381-7264',
    'Zip Code': '89102',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Condo',
    'Credit Score': '680-699',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Looking in 1-3 months',
    'Property Use': 'Primary Residence',
    'Purchase Price': '310000',
    'Down Payment': '15500',
    'Rate Type': 'Fixed',
    'Annual Income': '76000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Social Media',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-11',
    'Time Submitted': '01:00 PM',
    'Browser': 'Firefox',
    'Submitted At': '2026-03-11T13:00:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 20. Kevin Lewis ── Closed ──────────────────────────────────────────────
  {
    rowNumber: 21,
    'Date': '2026-03-10',
    'First Name': 'Kevin',
    'Last Name': 'Lewis',
    'Email': 'kevin.lewis@gmail.com',
    'Phone': '(702) 547-9321',
    'Zip Code': '89141',
    'Loan Type': 'Home Refinance',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '720-739',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '465000',
    'Down Payment': '93000',
    'Rate Type': 'Fixed',
    'Annual Income': '128000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Sunnyhill Past Client Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-10',
    'Time Submitted': '03:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-10T15:00:00Z',
    'Status': 'Closed',
    'Notes': '[2026-03-10 15:00] Loan funded. Kevin refinanced and lowered payment by $380/mo. Has already referred a neighbor.\n[2026-01-11 10:00] Call completed. Looking to reduce monthly payment. Great profile.',
  },

  // ── 21. Samantha Lee ── Contacted ──────────────────────────────────────────
  {
    rowNumber: 22,
    'Date': '2026-03-05',
    'First Name': 'Samantha',
    'Last Name': 'Lee',
    'Email': 'samantha.lee@gmail.com',
    'Phone': '(702) 829-4615',
    'Zip Code': '89138',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '760-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '510000',
    'Down Payment': '102000',
    'Rate Type': 'Fixed',
    'Annual Income': '148000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Google',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/purchase',
    'Date Submitted': '2026-03-05',
    'Time Submitted': '03:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-05T15:00:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-03-06 09:35] Intro email sent. Follow-up text sent 3/8. Interested in Summerlin area.',
  },

  // ── 22. Tyler Walker ── Qualified (2 days ago) ─────────────────────────────
  {
    rowNumber: 23,
    'Date': '2026-03-14',
    'First Name': 'Tyler',
    'Last Name': 'Walker',
    'Email': 'tyler.walker@gmail.com',
    'Phone': '(702) 634-8172',
    'Zip Code': '89128',
    'Loan Type': 'VA Loan',
    'VA Loan': 'Yes',
    'Property Type': 'Single Family',
    'Credit Score': '720-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '420000',
    'Down Payment': '0',
    'Rate Type': 'Fixed',
    'Annual Income': '98000',
    'Employment Status': 'Veteran',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Google',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/va-loan',
    'Date Submitted': '2026-03-14',
    'Time Submitted': '09:15 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-14T09:15:00Z',
    'Status': 'Qualified',
    'Notes': '[2026-03-16 09:15] VA pre-approval letter issued. COE verified.\n[2026-03-15 02:00 PM] Call completed. Veteran, first VA loan, very excited to get started.',
  },

  // ── 23. Nicole Hall ── New (submitted today) ───────────────────────────────
  {
    rowNumber: 24,
    'Date': '2026-03-16',
    'First Name': 'Nicole',
    'Last Name': 'Hall',
    'Email': 'nicole.hall@gmail.com',
    'Phone': '(702) 472-3895',
    'Zip Code': '89103',
    'Loan Type': 'HELOC/Equity',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '660-699',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '365000',
    'Down Payment': '36500',
    'Rate Type': 'Fixed',
    'Annual Income': '85000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'No',
    'How Found': 'Bankrate',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-16',
    'Time Submitted': '05:15 AM',
    'Browser': 'Safari',
    'Submitted At': '2026-03-16T05:15:00Z',
    'Status': 'New',
    'Notes': '',
  },

  // ── 24. Brandon Allen ── Closed ────────────────────────────────────────────
  {
    rowNumber: 25,
    'Date': '2026-03-12',
    'First Name': 'Brandon',
    'Last Name': 'Allen',
    'Email': 'brandon.allen@gmail.com',
    'Phone': '(702) 918-6347',
    'Zip Code': '89134',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '780-799',
    'First Time Buyer': 'No',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '580000',
    'Down Payment': '116000',
    'Rate Type': 'Fixed',
    'Annual Income': '175000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Zillow',
    'Rebel Path Lead': 'Yes',
    'Rebel Path URL': 'https://rebelpath.com/purchase',
    'Date Submitted': '2026-03-12',
    'Time Submitted': '04:00 PM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-12T16:00:00Z',
    'Status': 'Closed',
    'Notes': '[2026-03-12 04:00 PM] Loan funded. Brandon purchased a single family home in Summerlin. Smooth, fast transaction. Excellent client.\n[2026-01-23 11:00] Call completed. Strong income and assets. Ready to buy immediately.',
  },

  // ── 25. Kayla Young ── Contacted (today) ──────────────────────────────────
  {
    rowNumber: 26,
    'Date': '2026-03-16',
    'First Name': 'Kayla',
    'Last Name': 'Young',
    'Email': 'kayla.young@gmail.com',
    'Phone': '(702) 265-7483',
    'Zip Code': '89117',
    'Loan Type': 'Home Purchase',
    'VA Loan': 'No',
    'Property Type': 'Single Family',
    'Credit Score': '700-739',
    'First Time Buyer': 'Yes',
    'Purchase Situation': 'Ready to Buy',
    'Property Use': 'Primary Residence',
    'Purchase Price': '385000',
    'Down Payment': '77000',
    'Rate Type': 'Fixed',
    'Annual Income': '96000',
    'Employment Status': 'Employed',
    'Bankruptcy': 'No',
    'Proof of Income': 'Yes',
    'Real Estate Agent': 'Yes',
    'How Found': 'Realtor Referral',
    'Rebel Path Lead': 'No',
    'Rebel Path URL': '',
    'Date Submitted': '2026-03-16',
    'Time Submitted': '08:30 AM',
    'Browser': 'Chrome',
    'Submitted At': '2026-03-16T08:30:00Z',
    'Status': 'Contacted',
    'Notes': '[2026-03-16 08:40] Intro email sent immediately. Hot new lead from realtor referral. Following up by phone.',
  },
]

// Helper: get full name from a lead object
export function getFullName(lead) {
  const first = lead['First Name'] || ''
  const last = lead['Last Name'] || ''
  return `${first} ${last}`.trim()
}
